image: gitlab.dylanwilson.dev:5050/infrastructure/kitchen-base:latest

before_script:
  - ln -s $PILLAR_DOCKER_REGISTRIES pillar/docker.sls
  - ln -s $PILLAR_LETSENCRYPT_DNS pillar/letsencrypt.sls
  - bundler install

test:
  stage: test
  script:
    - bundler exec kitchen test
