stages:
  - test

test:
  stage: test
  before_script:
    - ln -s $PILLAR_DOCKER_REGISTRIES pillar/docker.sls
    - ln -s $PILLAR_LETSENCRYPT_DNS pillar/letsencrypt.sls
    - export PATH="$HOME/.rbenv/bin:$PATH"
    - eval "$(rbenv init -)"
    - gem install bundler
    - rbenv rehash
    - bundler install
  script:
    - bundler exec kitchen test
